version: '3'

services:
  nginx:
    container_name: ceom-load-balancer
    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      - ../CERTS:/CERTS
    
    ports:
      - 80:80
      - 443:443
      